export default {
    tickets : [
    {
        train_code : 'G6313',
        start_time : '7:30',
        interval : '00:29',
        from_name : '广州南',
        to_name : '深圳北',
        seat_first_class : '有', 
        seat_second_class : '有',
        seat_stand : '--',
    },
    {
        train_code : 'G6314',
        start_time : '8:45',
        interval : '00:36',
        from_name : '广州南',
        to_name : '深圳北',
        seat_first_class : '有', 
        seat_second_class : '无',
        seat_stand : '--',
    },
    {
        train_code : 'G6315',
        start_time : '9:40',
        interval : '00:36',
        from_name : '广州南',
        to_name : '深圳北',
        seat_first_class : '有', 
        seat_second_class : '有',
        seat_stand : '有',
    },
    {
        train_code : 'G6315',
        start_time : '9:40',
        interval : '00:36',
        from_name : '广州南',
        to_name : '深圳北',
        seat_first_class : '有', 
        seat_second_class : '有',
        seat_stand : '有',
    },
    ],

};